#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build
npm run build:index

SEDOPTION='-i'
if [[ "$OSTYPE" == "darwin"* ]]; then
  SEDOPTION="-i ''"
fi

for k in $(jq '.tutorials | keys | .[]' tutorials.json); do
  name=$(jq -r ".tutorials[$k].name" tutorials.json);
  link=$(jq -r ".tutorials[$k].link" tutorials.json);
  description=$(jq -r ".tutorials[$k].description" tutorials.json);

  cd $link
  rm -rf build
  npm run build
  cd ..
  cp -R "${link}/build" "build/${link}"

  sed $SEDOPTION -e "/<head>/p; s/<head>/<title>${name}<\/title>/" build/${link}/index.html 
  sed $SEDOPTION -e "/<head>/p; s/<head>/<meta name='description' content='${description}'><\/meta>/" build/${link}/index.html 

  sed $SEDOPTION -e "/<\/head>/p; s/<\/head>/<\/div>/" build/${link}/index.html 

  # Add name
  sed $SEDOPTION -e "/<\/head>/p; s/<\/head>/<h1 style = 'margin-bottom: 2rem; margin-top: 2rem;' >${name}<\/h1>/" build/${link}/index.html 

  # Add link to code
  sed $SEDOPTION -e "/<\/head>/p; s/<\/head>/<a style='padding-left: 1rem;' href=\'https:\/\/github.com\/stevesdodd\/sd-games\/tree\/master\/${link}'>Code<\/a>/" build/${link}/index.html 

  # Add link to blog
  sed $SEDOPTION -e "/<\/head>/p; s/<\/head>/<a style='padding-left: 1rem;' href=\'https:\/\/stephendoddtech.com\/blog\/game-design\/${link}'>Blog<\/a>/" build/${link}/index.html 

  # Add link to my website
  sed $SEDOPTION -e '/<\/head>/p; s/<\/head>/<a style="padding-left: 1rem;" href=\"https:\/\/stephendoddtech.com\/category\/game-design">Stephen Dodd Tech Game Development<\/a>/' build/${link}/index.html 

  # Add back link
  sed $SEDOPTION -e '/<\/head>/p; s/<\/head>/<a href=\"..\/\">Back<\/a>/' build/${link}/index.html 

  # Add header  
  sed $SEDOPTION -e '/<\/head>/p; s/<\/head>/<div id="header" style="margin-bottom: 2rem; background: rgb(255,207,160); background: linear-gradient(180deg, rgba(255,207,160,1) 10%, rgba(246,151,29,1) 93%); height: 140px; display: flex; justify-content: center; align-items: center;"><h2 style="color: white; font-size: 3rem;">Stephen Dodd Game Tutorials<\/h2><\/div>/' build/${link}/index.html 

  sed $SEDOPTION -e "/<\/head>/p; s/<\/head>/<div class='hide'>/" build/${link}/index.html 

  # Add footer
  sed $SEDOPTION -e "s/<\/canvas>/<\/canvas><div class='hide' style='display: flex; padding: 1rem; align-items: center; background: #212832; color: #F0F2F5; height: 80px'>© Stephen Dodd 2022<\/div>/" build/${link}/index.html 
 
  # Add description  
  sed $SEDOPTION -e "s/<\/canvas>/<\/canvas><div style='padding: 1rem; margin: 1rem;' class='hide'><p>${description}<\/p><\/div>/" build/${link}/index.html 

  # Remove hidable elements
  sed $SEDOPTION -e 's/<\/script>/<\/script><script>const path = window.location.href; if (path.includes("hide=true")) { const a = document.getElementsByClassName("hide"); for (var i = 0; i < a.length; i++) { a[i].style.display = "none";}; }<\/script>/' build/${link}/index.html 

done
