#!/bin/bash
set -euo pipefail

middle=''

a=''
head=$(cat head.html)
tail=$(cat tail.html)

for k in $(jq '.tutorials | keys | .[]' tutorials.json); do
  name=$(jq -r ".tutorials[$k].name" tutorials.json);
  link=$(jq -r ".tutorials[$k].link" tutorials.json);
  description=$(jq -r ".tutorials[$k].description" tutorials.json);

  a+="<div><div>$name <a href='https://stevesdodd.github.io/sd-games/${link}'>Example</a> <a href='https://github.com/stevesdodd/sd-games/tree/master/${link}'>Code</a> <a href='https://stephendoddtech.com/blog/game-design/$link'>Blog</a></div><div>${description}</div></div>"

done

echo $head$a$tail > index.html
